accounts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
app_name = 'accounts'

urlpatterns = [
    path('',
        auth_views.LoginView.as_view(template_name='login.html'),
        name='login'),

    path('signup/', views.SignUpView.as_view(), name='signup'),

    path('logout/',
         auth_views.LogoutView.as_view(next_page=reverse_lazy('accounts:login')),
         name='logout'),
    
    path('login_guest/',
         views.GuestUserView.as_view(),
         name='login_guest'),

]

taskapp/urls.py
from django.urls import path
from . import views

app_name = 'taskapp'

urlpatterns = [
    path('', views.FormAndListView.as_view(), name='index'),
    path('task/<int:pk>/detail/', views.task_detail, name='task_detail'),
    path('delete_task/<int:task_id>/', views.delete_task, name='delete_task'),
    ]

taskproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('taskapp/', include('taskapp.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    pass

taskapp/models.py
from django.db import models
from accounts.models import CustomUser

class Task(models.Model):
    
    class Priority(models.IntegerChoices):
        LOWEST = 1, "1(Lowest)"
        LOW = 2, "2(Low)"
        MEDIUM = 3, "3(middle)"
        HIGH = 4, "4(High)"
        HIGHEST = 5, "5(Highest)"

    user = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        )
    
    task_name = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        )
    
    details = models.TextField()
    
    date = models.DateField()
    
    priority = models.IntegerField(
        choices=Priority.choices,
        default=Priority.MEDIUM,
        )
    
    def __str__(self):
        return self.task_name

accounts/forms.py
from django import forms
from .models import CustomUser
from django.core.exceptions import ValidationError

class CustomUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="パスワード", widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('username', 'password')

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if CustomUser.objects.filter(username=username).exists():
            raise ValidationError('このユーザーネームは既に使用されています。')
        return username

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 8:
            raise ValidationError('パスワードは8文字以上である必要があります。')
        return password

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user

taskapp/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['task_name', 'details', 'date', 'priority']

accounts/views.py
from django.views import generic
from django.views import View
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate 
from django.shortcuts import redirect
from .models import CustomUser

class SignUpView(generic.CreateView):
   form_class = CustomUserCreationForm
   success_url = reverse_lazy('accounts:login')
   template_name = 'signup.html'

   def form_valid(self, form):
      user = form.save()
      self.object = user
      return super().form_valid(form)

class GuestUserView(View):
   def get(self, request):
      if not request.session.session_key:
         request.session.create()
      request.session.set_expiry(0)
      guest_username = f"guest_{request.session.session_key}"
      user = CustomUser(username=guest_username)
      user.set_unusable_password()
      user.save()
      login(request, user)
      return redirect('taskapp:index')

taskapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView
from .models import Task
from .forms import TaskForm
from django.http import JsonResponse

class FormAndListView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        order = self.request.GET.get('order', 'pk')
        
        order_options = {
            'pk': 'pk',
            'priority': '-priority',
            'date': 'date',
        }

        context['tasks'] = Task.objects.filter(user=self.request.user).order_by(order_options.get(order, 'pk'))
        context['form'] = kwargs.get('form', TaskForm())
        context['is_guest_user'] = self.request.user.username.startswith("guest_")
        context['selected_order'] = order
        return context

    def post(self, request, *args, **kwargs):
        form = TaskForm(request.POST)
        postdata = form.save(commit=False)
        if form.is_valid():
            postdata.user = self.request.user
            form.save()
            return redirect('taskapp:index')
        return render(request, self.template_name, self.get_context_data(form=form))


def task_detail(request, pk):
        task = get_object_or_404(Task, pk=pk)
        return render(request, 'task_detail.html', {'task': task})

def delete_task(request, task_id):
    if request.method == 'POST':
        task = get_object_or_404(Task, pk=task_id)
        task.delete()
        return JsonResponse({'message': 'タスクが削除されました'})
    return JsonResponse({'message': '無効なリクエスト'}, status=400)

accounts/templates/login.html
{% extends "base.html" %}

{% block title %}login{% endblock %}

{% block content %}
    <div class="account_content">
    <form method="post" id="account">
        {% csrf_token %}
        {% if form.errors %}
        <p style="color: red;">ユーザー名とパスワードが一致しません。</p>
        {% endif %}
        <h1 id="account_title">login</h1>
        <p>
            <label for="id_username">username</label>
            <input type="text" name="username" id="id_username" required autofocus>
        </p>
        <p>
            <label for="id_password">password</label>
            <input type="password" name="password" id="id_password" required autofocus>
        </p>
        <input type="submit" value="login">
        <p>
            <a href="{% url 'accounts:signup' %}">Sign up</a>
            <br>
            <a href="{% url 'accounts:login_guest' %}">guest user</a>
        </p>
    </form>
    </div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}

{% block title %}新規登録{% endblock %}

{% block content %}
    <div class="account_content">
    <form method = "post" id="account">
        {% csrf_token %}
        {% if form.errors %}
            <div style="color: red;">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <h1 id="account_title">Sign up</h1>
        <p>
            <label for="id_username">username</label>
            <input type="text" name="username" id="id_username" requierd autofocus>
        </p>
        <p>
            <label for="id_password">password</label>
            <input type="password" name="password" id="id_password" required autofocus>
        </p>
        <input type="submit" value="Sign up">
        <p>
            <a href="{% url 'accounts:login' %}">login</a>
            <br>
            <a href="{% url 'accounts:login_guest' %}">login as guest</a>
        </p>
    </form>
    </div>
{% endblock %}

taskapp/templates/add_task.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            <tr>
                <th><label for="task_name">タイトル</label></th>
                <td><input type="text" name="task_name" id="task_name" class="input_form" required autofocus></td>
            </tr>

            <tr class="line">
                <th><label for="details">詳細</label></th>
                <td><textarea name="details" rows="4" col="50" class="input_form" required></textarea></td>
            </tr>

            <tr class="line">
                <th><label for="date">期限</label></th>
                <td><input type="date" name="date" id="date" class="input_form" required></td>
            </tr>

            <tr class="line">
                <th><label for="priority">優先度</label></th>
                <td>
                    <input type="range" min="1" max="5" value="3" name="priority" id="priority" class="input_form" required>
                    <span id="rangeValue">3</span>
                    <br>
                    数値が大きいほど優先度が高いです
                </td>
            </tr>

        </table>

</body>
</html>

taskapp/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
    <header>
        <div class="hamburger">
            <div></div>
            <div></div>
            <div></div>
        </div>
        <div class="menu">
            {% if user.is_authenticated %}
                <a href="{% url 'accounts:logout' %}">ログアウト</a>
            {% else %}
                <a href="{% url 'accounts:signup' %}">新規登録</a>
                <a href="{% url 'accounts:login' %}">ログイン</a>
            {% endif %}
        </div>
    </header>

        {% block content %}
        {% endblock %}

    <footer>
        <p>&copy; 2025 task-manageapp</p>
    </footer>

    <script>
        document.querySelector('.hamburger').addEventListener('click', function() {
            const menu = document.querySelector('.menu');
            
            menu.style.animation = 'none';
            menu.offsetHeight;
            menu.style.animation = '';
    
            if (menu.classList.contains('openmenu')) {
                menu.classList.remove('openmenu');
                menu.classList.add('closemenu');
                menu.addEventListener('animationend', function() {
                    menu.style.display = 'none';
                    menu.classList.remove('closemenu');
                }, { once: true });
            } else {
                menu.style.display = 'block';
                menu.classList.add('openmenu');
            }
        });
    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static "js/slider.js" %}"></script>
    <script src="{% static "js/sort.js" %}"></script>
    <script src="{% static "js/modal.js" %}"></script>
    
</body>
</html>

taskapp/templates/index.html
{% extends "base.html" %}

{% block title %}task_management{% endblock %}

{% block head %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">{% endblock %}

{% block content %}
<div class="content">


    <div class="control-bar">
        {% if is_guest_user %}
            <p>ゲストさん</p>
        {% else %}
            <p>{{ user }}さん</p>
        {% endif %}
        <button type="submit" data-toggle="modal" data-target="#myModal">タスク追加</button>
        <div class="dropdown" id="dropdown">
            <button class="dropbtn" id="order-title">並び替え ▼</button>
            <div class="dropdown-content">
                <button onclick="sortTasks('pk')">追加順</button>
                <button onclick="sortTasks('priority')">優先度順</button>
                <button onclick="sortTasks('date')">期限順</button>
            </div>
        </div>
    </div>

    <div id="task-list">
        {% for task in tasks %}
        <div class="task-row">
            <div class="task-priority priority-{{ task.priority }}"></div>

            <a href="#" class="task-detail-link" data-toggle="modal" data-target="#taskDetailModal"
                data-task-id="{{ task.pk }}"
                data-task-name="{{ task.task_name }}"
                data-task-details="{{ task.details }}"
                data-task-date="{{ task.date|date:"Y-m-d" }}"
                data-task-priority="{{ task.get_priority_display }}">
                {{ task.task_name|truncatechars:15 }}
            </a>
            <span><small>期限: </small>{{ task.date|date:"Y-m-d" }}</span>
        </div>
        {% endfor %}
    </div>
    

    <div class="priority-legend">
        <span><small>優先度：</small></span>
        <span class="priority-box green"></span>
        <span>&lt;</span>
        <span class="priority-box light-green"></span>
        <span>&lt;</span>
        <span class="priority-box yellow"></span>
        <span>&lt;</span>
        <span class="priority-box orange"></span>
        <span>&lt;</span>
        <span class="priority-box red"></span>
    </div>
    

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="myModalLabel">タスク追加</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% include 'add_task.html' %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">close</button>
                    <input type="submit" class="btn btn-secondary" id="add_task" value="add">
                </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="taskDetailModal" tabindex="-1" role="dialog" aria-labelledby="taskDetailModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="taskDetailModalLabel">タスク詳細</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% include 'task_detail.html' %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

taskapp/templates/task_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
</head>

<body>
    <table>
        <tr>
            <th>タイトル:</th>
            <td id="modal-task-name"></td>
        </tr>
        <tr class="line">
            <th>詳細:</th>
            <td id="modal-task-details"></td>
        </tr>
        <tr class="line">
            <th>期限:</th>
            <td id="modal-task-date"></td>
        </tr>
        <tr class="line">
            <th>優先度:</th>
            <td id="modal-task-priority"></td>
        </tr>
    </table>
    
    <div class="modal-footer">
        <button id="delete-task-btn" data-task-id="{{ task.pk }}" class="btn btn-danger">削除</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
    </div>


</body>
</html>